# Numpy Crash Course


In [ ]:
import numpy as np

Numpy Array Definition
--

In [220]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [221]:
X=np.zeros(5)
X.shape

(5,)

In [222]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [223]:
X=np.zeros((1,5))
X.shape

(1, 5)

In [224]:
X=np.zeros((1,5))
X.size

5

In [225]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [226]:
X=np.zeros((5,1))
X.shape

(5, 1)

In [227]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [228]:
X=np.zeros((4,2))
X.shape

(4, 2)

In [229]:
X=np.zeros((4,2))
X.size

8

In [230]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [231]:
np.random.rand(4,2)

array([[0.71822861, 0.02647561],
       [0.28706138, 0.56408881],
       [0.96825307, 0.97441647],
       [0.83604831, 0.01603413]])

In [232]:
np.random.randn(4,2)

array([[ 1.85962064,  0.71108053],
       [-0.94919339,  0.62055794],
       [-1.30875892,  0.59684811],
       [-0.00248174,  0.07309672]])

In [233]:
np.random.randint(0,10,size=(4,2))

array([[2, 0],
       [5, 5],
       [6, 2],
       [6, 6]])

In [234]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [235]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [236]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [239]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

## Numpy Array Reshaping

In [240]:
x=np.zeros(5)
x.shape

(5,)

In [241]:
x.reshape((x.size,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [242]:
x.reshape((1,x.size))

array([[0., 0., 0., 0., 0.]])

In [243]:
X=np.arange(8)
X

array([0, 1, 2, 3, 4, 5, 6, 7])

In [244]:
X=X.reshape((4,2))
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [245]:
X.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Numpy Array Indexing and Slicing

In [246]:
X=np.random.randint(-10,10,size=(2,5))
X

array([[-6,  0, -8, -2,  5],
       [ 7, -3,  4,  3, -4]])

In [249]:
X[0]

array([-6,  0, -8, -2,  5])

In [250]:
X[0,0]

-6

In [253]:
X[0,:]

array([-6,  0, -8, -2,  5])

In [256]:
X[[0],:]

array([[-6,  0, -8, -2,  5]])

In [260]:
X[:,[0,2,4]]

array([[-6, -6,  5],
       [ 7,  7, -4]])

In [262]:
X

array([[-6,  0, -8, -2,  5],
       [ 7, -3,  4,  3, -4]])

In [261]:
Y=X[0,:]>=0
Y

array([False,  True, False, False,  True])

In [268]:
X[:,Y]

array([[ 0,  5],
       [-3, -4]])

## Numpy Elementwise Functions

In [269]:
X=np.random.randn(2,3)
X

array([[-0.87089371, -1.77666223, -0.42180788],
       [ 0.26628951,  0.82124237, -0.76400272]])

In [270]:
2*X

array([[-1.74178742, -3.55332446, -0.84361576],
       [ 0.53257901,  1.64248475, -1.52800544]])

In [271]:
X+5

array([[4.12910629, 3.22333777, 4.57819212],
       [5.26628951, 5.82124237, 4.23599728]])

In [272]:
X**2

array([[0.75845585, 3.15652868, 0.17792189],
       [0.0709101 , 0.67443904, 0.58370015]])

In [273]:
np.abs(X)

array([[0.87089371, 1.77666223, 0.42180788],
       [0.26628951, 0.82124237, 0.76400272]])

In [274]:
np.sin(X)

array([[-0.76490492, -0.97888435, -0.40941054],
       [ 0.26315354,  0.73199284, -0.69181723]])

In [275]:
np.exp(X)

array([[0.4185773 , 0.16920196, 0.65586003],
       [1.30511284, 2.2733224 , 0.46579823]])

In [276]:
np.log(1+np.exp(-X))

array([[1.22054817, 1.93298366, 0.92612841],
       [0.56884012, 0.36456312, 1.14640268]])

## Numpy Reduction Operations

In [277]:
X=np.random.randint(0,10,size=(2,5))
X

array([[4, 4, 8, 5, 8],
       [1, 6, 0, 1, 0]])

In [278]:
X.sum()

37

In [279]:
X.sum(axis=0)

array([ 5, 10,  8,  6,  8])

In [280]:
X.sum(axis=1)

array([29,  8])

In [281]:
X.sum(axis=1,keepdims=True)

array([[29],
       [ 8]])

In [282]:
X.prod(axis=1,keepdims=True)

array([[5120],
       [   0]])

In [283]:
X.mean(axis=1,keepdims=True)

array([[5.8],
       [1.6]])

In [284]:
X.std(axis=1,keepdims=True)

array([[1.83303028],
       [2.24499443]])

In [285]:
X.max(axis=1,keepdims=True)

array([[8],
       [6]])

In [286]:
X.argmax(axis=1,keepdims=True)

array([[2],
       [1]])

## Why Use Reductions?

In [287]:
N = 10000
X = np.random.randn(N) 
print(X.shape)

(10000,)


In [288]:
def sum(X):
    sum_X = 0.
    for i in range(N):
        sum_X += X[i]
    return sum_X

print(sum(X))
%timeit sum(X)

-70.53360785407655
698 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [289]:
print(np.sum(X))
%timeit np.sum(X)

-70.53360785407656
3.11 µs ± 7.14 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Numpy Linear Algebra

In [290]:
Y = np.array([[2,2]])
Y

array([[2, 2]])

In [291]:
Z = np.array([[-2,2]])
Z

array([[-2,  2]])

In [292]:
Y+Z

array([[0, 4]])

In [293]:
Y*Z

array([[-4,  4]])

In [297]:
Y.T

array([[2],
       [2]])

In [298]:
Z.dot(Y.T)

array([[0]])

In [299]:
np.sum(Z*Y,keepdims=True)

array([[0]])

In [300]:
X=np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [303]:
X.dot(Z.T)

array([[2],
       [2],
       [2]])

In [304]:
X.dot(X.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [305]:
X.T.dot(X)

array([[35, 44],
       [44, 56]])

In [306]:
XTX    = X.T.dot(X)
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 2.33333333, -1.83333333],
       [-1.83333333,  1.45833333]])

In [307]:
(XTX).dot(XTXinv)

array([[1.00000000e+00, 1.77635684e-15],
       [1.59872116e-14, 1.00000000e+00]])

## Numpy Broadcasting

In [308]:
Z = np.array([[-2,1,2]]).T
Z

array([[-2],
       [ 1],
       [ 2]])

In [309]:
X=np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [310]:
X+Z

array([[-1,  0],
       [ 4,  5],
       [ 7,  8]])

In [311]:
Z[:,[0,0]] + X

array([[-1,  0],
       [ 4,  5],
       [ 7,  8]])

In [312]:
X*Z

array([[-2, -4],
       [ 3,  4],
       [10, 12]])

In [313]:
Y=np.array([[1,2,3]])
Y

array([[1, 2, 3]])

In [314]:
Y+Z

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [315]:
Y*Z

array([[-2, -4, -6],
       [ 1,  2,  3],
       [ 2,  4,  6]])

## Example: Vectorized Numpy Linear Regression

In [ ]:
from scipy.optimize import approx_fprime, minimize
import numpy as np

In [316]:
N = 100
X = np.hstack((np.random.rand(N,2), np.ones((N,1))))
theta = np.array([[-1,1,2]]).T
Y = X.dot(theta) + np.random.randn(N,1)/5.0 

Prediction Function: $ f_{\theta}(x) = x\theta$

In [317]:
def f1(theta,X):
    theta = theta.reshape((theta.size,1))
    N,D = X.shape

    out = np.zeros((N,1))
    for n in range(N):
        for d in range(D):
            out[n,0] += X[n,d]*theta[d,0]

    return out

%timeit f1(theta,X)
out=f1(theta,X)
print(out[:5,0])

108 µs ± 1.68 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
[2.41383876 1.70089004 1.74439538 1.705842   1.72970873]


In [318]:
def f2(theta,X):
    theta = theta.reshape((theta.size,1))
    N,D = X.shape

    out = np.zeros((N,1))
    for n in range(N):
            out[n,0] = X[[n],:].dot(theta)
    return out

out=f2(theta,X)
%timeit f2(theta,X)
print(out[:5,0])

150 µs ± 2.41 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
[2.41383876 1.70089004 1.74439538 1.705842   1.72970873]


In [319]:
def f(theta,X):
    theta = theta.reshape((theta.size,1))
    return X.dot(theta)

out=f(theta,X)
%timeit f(theta,X)
print(out[:5,0])

907 ns ± 14.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
[2.41383876 1.70089004 1.74439538 1.705842   1.72970873]


Risk Function: $\frac{1}{N}\sum_{n=1}^N (y_n - f_{\theta}(x_n))^2$

In [ ]:
def risk(theta,X,Y):
    theta = theta.reshape((theta.size,1))
    return np.mean((Y-f(theta,X))**2)

risk(theta,X,Y)

Risk Gradient: $\frac{-2}{N}\sum_{n=1}^N (y_n-f_{\theta}(x_n))x_n^T = \frac{-2}{N}\sum_{n=1}^N ((y_n-f_{\theta}(x_n))x_n)^T$

In [ ]:
def riskGrad(theta,X,Y):    
    Z  = ((Y-f(theta,X))*X).T
    return -2*np.mean(Z,axis=1,keepdims=True)

riskGrad(theta,X,Y)

In [ ]:
theta0 = np.random.randn(3,)
approx_fprime(theta0,risk,1e-6,X,Y) 

In [ ]:
riskGrad(theta0,X,Y)

Fit: $\hat{\theta} = (X^TX)^{-1}X^TY$

In [ ]:
def fit(X,Y):
    return np.linalg.inv(X.T.dot(X)).dot(X.T.dot(Y))

fit(X,Y)

Fit: Using Minimize

In [ ]:
def fit(X,Y):
    N,D = X.shape
    theta0=np.zeros(D,)
    out = minimize(risk, theta0, args=(X,Y), method="L-BFGS-B", jac=riskGrad,tol=1e-6, options={"disp":True})
    return out.x.reshape((D,1)), out

theta_hat,out =fit(X,Y)

In [ ]:
theta_hat

In [ ]:
out