# Numpy Crash Course


In [ ]:
import numpy as np

Numpy Array Definition
--

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
x=np.zeros(5)
x.shape

(5,)

In [6]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [40]:
x=np.zeros((1,5))
x.shape

(1, 5)

In [210]:
x=np.zeros((1,5))
x.size

5

In [41]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [43]:
X=np.zeros((5,1))
X.shape

(5, 1)

In [44]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [211]:
X=np.zeros((4,2))
X.shape

(4, 2)

In [212]:
X=np.zeros((4,2))
X.size

8

In [45]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [46]:
np.random.rand(4,2)

array([[0.72404512, 0.32658997],
       [0.35143289, 0.64917107],
       [0.21874603, 0.26599329],
       [0.56952569, 0.34488125]])

In [47]:
np.random.randn(4,2)

array([[-0.2530101 ,  0.71055892],
       [ 0.68412162,  0.70993198],
       [ 0.62444114,  2.90245855],
       [ 0.01445426, -0.21042171]])

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [14]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [15]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

## Numpy Array Reshaping

In [214]:
x=np.zeros(5)
x.shape

(5,)

In [215]:
x.reshape((x.size,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [216]:
x.reshape((1,x.size))

array([[0., 0., 0., 0., 0.]])

In [220]:
X=np.arange(8)
X

array([0, 1, 2, 3, 4, 5, 6, 7])

In [222]:
X=X.reshape((4,2))
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [223]:
X.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Numpy Array Slicing

In [49]:
X = np.arange(5)
X[:3]

array([0, 1, 2])

In [50]:
X = np.arange(5)
X[3:]

array([3, 4])

In [51]:
X = np.arange(5)
X[:-1]

array([0, 1, 2, 3])

In [16]:
X=np.array([[1,2],[3,4],[5,6]])
X[0,:]

array([1, 2])

In [17]:
X=np.array([[1,2],[3,4],[5,6]])
X[:,1]

array([2, 4, 6])

In [18]:
 X=np.array([[1,2],[3,4],[5,6]])
 X[:,[1]]

array([[2],
       [4],
       [6]])

In [23]:
X=np.array([[1,2],[3,4],[5,6]])
X[1:,:]

array([[3, 4],
       [5, 6]])

## Numpy Array Indexing

In [71]:
X=np.random.randn(2,5)
X

array([[ 0.12544724,  2.13649379, -0.3284081 ,  1.20846544, -0.32886761],
       [-2.13448263,  1.59539773,  1.70218576, -0.08604635, -0.15174217]])

In [70]:
X[:,[0,2,4]]

array([[0.52146506, 0.30270767, 0.52631347],
       [0.63808251, 0.93765025, 0.74481123]])

In [72]:
Y=X>=0
Y

array([[ True,  True, False,  True, False],
       [False,  True,  True, False, False]])

In [73]:
X[Y]

array([0.12544724, 2.13649379, 1.20846544, 1.59539773, 1.70218576])

In [74]:
X[:,X[0,:]>0]

array([[ 0.12544724,  2.13649379,  1.20846544],
       [-2.13448263,  1.59539773, -0.08604635]])

## Numpy Elementwise Functions

In [76]:
X=np.random.randn(2,5)
X

array([[-0.44377252,  0.03141039,  1.81349462,  0.19474851,  1.81721433],
       [ 1.10383123, -0.07725059, -0.03352903, -2.14488246,  0.98134196]])

In [80]:
2*X

array([[-0.88754505,  0.06282077,  3.62698924,  0.38949701,  3.63442867],
       [ 2.20766245, -0.15450118, -0.06705807, -4.28976492,  1.96268392]])

In [81]:
X+5

array([[4.55622748, 5.03141039, 6.81349462, 5.19474851, 6.81721433],
       [6.10383123, 4.92274941, 4.96647097, 2.85511754, 5.98134196]])

In [82]:
X**2

array([[1.96934053e-01, 9.86612408e-04, 3.28876273e+00, 3.79269809e-02,
        3.30226794e+00],
       [1.21844337e+00, 5.96765371e-03, 1.12419616e-03, 4.60052077e+00,
        9.63032042e-01]])

In [77]:
np.abs(X)

array([[0.44377252, 0.03141039, 1.81349462, 0.19474851, 1.81721433],
       [1.10383123, 0.07725059, 0.03352903, 2.14488246, 0.98134196]])

In [83]:
np.sin(X)

array([[-0.42934962,  0.03140522,  0.97069305,  0.1935198 ,  0.9697924 ],
       [ 0.89293864, -0.07717378, -0.03352275, -0.83968894,  0.83124412]])

In [84]:
np.exp(X)

array([[0.64161136, 1.0319089 , 6.13183848, 1.21500538, 6.15468964],
       [3.01569774, 0.92565786, 0.96702683, 0.1170818 , 2.66803423]])

In [85]:
np.log(1+np.exp(-X))

array([[0.93945082, 0.67756531, 0.15107443, 0.60050633, 0.1505537 ],
       [0.28637989, 0.73251825, 0.71005222, 2.25560221, 0.31831393]])

## Numpy Reduction Operations

In [86]:
X=np.random.randn(2,5)
X

array([[ 0.22852485, -0.05024049, -0.26490274, -1.52037582, -0.74077909],
       [ 0.62832224,  0.73583824,  0.09836118,  0.83312632, -0.16717607]])

In [87]:
X.sum()

-0.2193013912988351

In [88]:
X.sum(axis=0)

array([ 0.85684708,  0.68559775, -0.16654156, -0.6872495 , -0.90795516])

In [89]:
X.sum(axis=1)

array([-2.34777329,  2.1284719 ])

In [90]:
X.sum(axis=1,keepdims=True)

array([[-2.34777329],
       [ 2.1284719 ]])

In [91]:
X.prod(axis=1,keepdims=True)

array([[ 0.00342542],
       [-0.00633393]])

In [92]:
X.mean(axis=1,keepdims=True)

array([[-0.46955466],
       [ 0.42569438]])

In [93]:
X.std(axis=1,keepdims=True)

array([[0.61364641],
       [0.39035636]])

In [94]:
X.max(axis=1,keepdims=True)

array([[0.22852485],
       [0.83312632]])

In [95]:
X.argmax(axis=1,keepdims=True)

array([[0],
       [3]])

## On The Importance of Using Reductions

In [96]:
N = 10000
X = np.random.randn(N) 
print(X.shape)

(10000,)


In [98]:
def sum(X):
    sum_X = 0.
    for i in range(N):
        sum_X += X[i]
    return sum_X

print(sum(X))
%timeit sum(X)

-127.6974681633566
705 µs ± 5.99 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [100]:
print(np.sum(X))
%timeit np.sum(X)

-127.69746816335632
3.24 µs ± 268 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Numpy Linear Algebra

In [113]:
Y = np.array([[2,2]])
Y

array([[2, 2]])

In [112]:
Z = np.array([[-2,2]])
Z

array([[-2,  2]])

In [114]:
Y+Z

array([[0, 4]])

In [115]:
Y*Z

array([[-4,  4]])

In [116]:
Y.T

array([[2],
       [2]])

In [117]:
Z.dot(Y.T)

array([[0]])

In [119]:
np.sum(Z*Y,keepdims=True)

array([[0]])

In [171]:
X=np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [173]:
X.dot(Z.T)

array([[2],
       [2],
       [2]])

In [174]:
X.dot(X.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [175]:
X.T.dot(X)

array([[35, 44],
       [44, 56]])

In [179]:
XTX    = X.T.dot(X)
XTXinv = np.linalg.inv(XTX)
XTXinv

array([[ 2.33333333, -1.83333333],
       [-1.83333333,  1.45833333]])

In [180]:
(XTX).dot(XTXinv)

array([[1.00000000e+00, 1.77635684e-15],
       [1.59872116e-14, 1.00000000e+00]])

## Numpy Broadcasting

In [228]:
Z = np.array([[-2,1,2]]).T
Z

array([[-2],
       [ 1],
       [ 2]])

In [224]:
X=np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [229]:
X+Z

array([[-1,  0],
       [ 4,  5],
       [ 7,  8]])

In [238]:
Z[:,[0,0]] + X

array([[-1,  0],
       [ 4,  5],
       [ 7,  8]])

In [239]:
X*Z

array([[-2, -4],
       [ 3,  4],
       [10, 12]])

In [240]:
Y=np.array([[1,2,3]])
Y

array([[1, 2, 3]])

In [241]:
Y+Z

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [242]:
Y*Z

array([[-2, -4, -6],
       [ 1,  2,  3],
       [ 2,  4,  6]])

## Example: Vectorized Numpy Linear Regression

In [197]:
from scipy.optimize import approx_fprime, minimize

In [245]:
N = 100
X = np.hstack((np.random.rand(N,2), np.ones((N,1))))
theta = np.array([[-1,1,2]]).T
Y = X.dot(theta) + np.random.randn(N,1)/5.0 

Prediction Function: $ f_{\theta}(x) = xw$

In [246]:
def f(theta,X):
    theta = theta.reshape((theta.size,1))
    return X.dot(theta)

f(theta,X)[:5]

array([[2.13029649],
       [1.51926919],
       [1.81034586],
       [1.88774141],
       [2.39804188]])

Risk Function: $\frac{1}{N}\sum_{n=1}^N (y_n - f_{\theta}(x_n))^2$

In [260]:
def risk(theta,X,Y):
    theta = theta.reshape((theta.size,1))
    return np.mean((Y-f(theta,X))**2)

risk(theta,X,Y)

0.03772314096059206

Risk Gradient: $\frac{-2}{N}\sum_{n=1}^N (y_n-f_{\theta}(x_n))x_n^T = \frac{-2}{N}\sum_{n=1}^N ((y_n-f_{\theta}(x_n))x_n)^T$

In [268]:
def riskGrad(theta,X,Y):    
    Z  = ((Y-f(theta,X))*X).T
    return -2*np.mean(Z,axis=1,keepdims=True)

riskGrad(theta,X,Y)

array([[-0.0288964 ],
       [-0.03728731],
       [-0.02414277]])

In [269]:
theta0 = np.random.randn(3,)
approx_fprime(theta0,risk,1e-6,X,Y) 

array([-0.45061922, -0.8928573 , -1.18125124])

In [270]:
riskGrad(theta0,X,Y)

array([[-0.45061962],
       [-0.89285763],
       [-1.18125224]])

In [271]:
def fit(X,Y):
    return np.linalg.inv(X.T.dot(X)).dot(X.T.dot(Y))

fit(X,Y)

array([[-0.91719829],
       [ 1.14716522],
       [ 1.89172201]])

In [272]:
out=minimize(risk, np.zeros(3,), args=(X,Y), method="L-BFGS-B", jac=riskGrad,tol=1e-6, options={"disp":True})
out

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            3     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.98109D+00    |proj g|=  3.88670D+00

At iterate    1    f=  6.96003D-01    |proj g|=  1.38315D+00

At iterate    2    f=  2.32870D-01    |proj g|=  2.09938D-01

At iterate    3    f=  1.56552D-01    |proj g|=  2.39354D-01

At iterate    4    f=  4.29859D-02    |proj g|=  8.56177D-02

At iterate    5    f=  3.54114D-02    |proj g|=  1.11041D-02

At iterate    6    f=  3.51501D-02    |proj g|=  9.35911D-03

At iterate    7    f=  3.51072D-02    |proj g|=  6.60476D-03

At iterate    8    f=  3.50903D-02    |proj g|=  5.55323D-04

At iterate    9    f=  3.50902D-02    |proj g|=  4.40697D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = nu

 This problem is unconstrained.


  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 0.03509017475286876
        x: [-9.173e-01  1.147e+00  1.892e+00]
      nit: 9
      jac: [[-3.511e-05]
            [-3.951e-05]
            [-4.407e-05]]
     nfev: 11
     njev: 11
 hess_inv: <3x3 LbfgsInvHessProduct with dtype=float64>